# Generated by Django 5.2.7 on 2025-10-24 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_rename_move_movie_alter_genre_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watch_history',
            old_name='move_id',
            new_name='movie_id',
        ),
    ]
