# Generated by Django 5.2.7 on 2025-10-31 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_rename_move_id_watch_history_movie_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
