# Generated by Django 5.2.8 on 2025-11-07 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
