# Generated by Django 5.2.8 on 2025-11-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_delete_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='def-img.png', upload_to=''),
        ),
    ]
