# Generated by Django 5.2.8 on 2025-11-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0007_alter_movie_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
