# Generated by Django 5.2.8 on 2025-11-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('1', 'admin'), ('2', 'meneger'), ('3', 'user')], default='user', max_length=10),
        ),
    ]
