# Generated by Django 5.2.8 on 2025-11-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_myuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_admin',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('1', 'admin'), ('2', 'manager'), ('3', 'user')], default='user', max_length=10),
        ),
    ]
